# Generated by Django 5.2.4 on 2025-07-18 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_punch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "特休"),
                            ("SICK", "病假"),
                            ("PERSONAL", "事假"),
                            ("MARRIAGE", "婚假"),
                            ("FUNERAL", "喪假"),
                            ("MATERNITY", "產假"),
                            ("PATERNITY", "陪產假"),
                            ("PUBLIC", "公假"),
                            ("COMPENSATORY", "補休"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待審核"),
                            ("APPROVED", "已核准"),
                            ("REJECTED", "已拒絕"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("applied_date", models.DateField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
            ],
        ),
    ]
