# Generated by Django 5.2.4 on 2025-07-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_leave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punch",
            name="punch_time",
            field=models.DateTimeField(),
        ),
    ]
