# Generated by Django 5.2.4 on 2025-07-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_alter_punch_punch_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="起始日期")),
                ("end_date", models.DateField(verbose_name="結束日期")),
                ("pay_date", models.DateField(verbose_name="發薪日")),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="已處理"),
                ),
                (
                    "processed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="處理日期"
                    ),
                ),
            ],
            options={
                "verbose_name": "薪資期間",
                "verbose_name_plural": "薪資期間",
            },
        ),
        migrations.CreateModel(
            name="SalaryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="項目名稱")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("ALLOWANCE", "加給"),
                            ("DEDUCTION", "扣除"),
                            ("BONUS", "獎金"),
                        ],
                        max_length=10,
                        verbose_name="項目類型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="固定金額",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="如果是百分比計算，請填入百分比數值",
                        max_digits=5,
                        null=True,
                        verbose_name="百分比",
                    ),
                ),
                (
                    "is_fixed",
                    models.BooleanField(default=True, verbose_name="固定項目"),
                ),
                (
                    "apply_to_parttime",
                    models.BooleanField(
                        default=False,
                        help_text="此項目是否適用於兼職人員",
                        verbose_name="適用兼職",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="說明")),
            ],
            options={
                "verbose_name": "薪資項目",
                "verbose_name_plural": "薪資項目",
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="班別名稱")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "固定班"),
                            ("FLEX", "彈性班"),
                            ("SHIFT", "輪班"),
                            ("PT", "兼職班"),
                        ],
                        max_length=10,
                        verbose_name="班別類型",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="預設上班時間")),
                ("end_time", models.TimeField(verbose_name="預設下班時間")),
                (
                    "break_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="休息開始時間"
                    ),
                ),
                (
                    "break_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="休息結束時間"
                    ),
                ),
                (
                    "is_night_shift",
                    models.BooleanField(default=False, verbose_name="夜班"),
                ),
                (
                    "flex_time_start",
                    models.TimeField(
                        blank=True,
                        help_text="彈性班別可設定彈性上下班時間區間",
                        null=True,
                        verbose_name="彈性上班時間起始",
                    ),
                ),
                (
                    "flex_time_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="彈性上班時間結束"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="說明")),
            ],
            options={
                "verbose_name": "工作班別",
                "verbose_name_plural": "工作班別",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "員工", "verbose_name_plural": "員工"},
        ),
        migrations.AlterModelOptions(
            name="salary",
            options={"verbose_name": "薪資紀錄", "verbose_name_plural": "薪資紀錄"},
        ),
        migrations.AddField(
            model_name="employee",
            name="active",
            field=models.BooleanField(default=True, verbose_name="在職狀態"),
        ),
        migrations.AddField(
            model_name="employee",
            name="base_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="僅適用於正職員工",
                max_digits=10,
                null=True,
                verbose_name="基本薪資",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[("FT", "正職"), ("PT", "兼職")],
                default="FT",
                max_length=2,
                verbose_name="僱用類型",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="僅適用於兼職員工",
                max_digits=10,
                null=True,
                verbose_name="時薪",
            ),
        ),
        migrations.AddField(
            model_name="salary",
            name="base_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="基本薪資/時薪總額",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salary",
            name="is_confirmed",
            field=models.BooleanField(default=False, verbose_name="已確認"),
        ),
        migrations.AddField(
            model_name="salary",
            name="overtime_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="加班費"
            ),
        ),
        migrations.AddField(
            model_name="salary",
            name="overtime_hours",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=5, verbose_name="加班時數"
            ),
        ),
        migrations.AddField(
            model_name="salary",
            name="working_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="兼職人員使用",
                max_digits=5,
                verbose_name="工作時數",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.department",
                verbose_name="部門",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="電子郵件"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(verbose_name="到職日期"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=100, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="電話"),
        ),
        migrations.AlterField(
            model_name="salary",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.employee",
                verbose_name="員工",
            ),
        ),
        migrations.AddField(
            model_name="salary",
            name="period",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.payrollperiod",
                verbose_name="薪資期間",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="salary",
            unique_together={("employee", "period")},
        ),
        migrations.CreateModel(
            name="SalaryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金額"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="說明"),
                ),
                (
                    "salary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.salary",
                        verbose_name="薪資紀錄",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employee.salaryitem",
                        verbose_name="薪資項目",
                    ),
                ),
            ],
            options={
                "verbose_name": "薪資明細",
                "verbose_name_plural": "薪資明細",
            },
        ),
        migrations.CreateModel(
            name="EmployeeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="生效日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="結束日期"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="員工的預設班別",
                        verbose_name="主要班別",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                        verbose_name="員工",
                    ),
                ),
                (
                    "work_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.workschedule",
                        verbose_name="班別",
                    ),
                ),
            ],
            options={
                "verbose_name": "員工班別",
                "verbose_name_plural": "員工班別",
            },
        ),
        migrations.RemoveField(
            model_name="salary",
            name="base_salary",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="bonus",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="deductions",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="pay_date",
        ),
    ]
