# Generated by Django 5.2.4 on 2025-07-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_payrollperiod_salaryitem_workschedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部門', 'verbose_name_plural': '部門'},
        ),
        migrations.AlterField(
            model_name='punch',
            name='punch_type',
            field=models.CharField(choices=[('IN', '上班'), ('OUT', '下班')], max_length=3),
        ),
    ]
