# Generated by Django 5.2.4 on 2025-07-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_department_options_alter_punch_punch_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name': '請假記錄', 'verbose_name_plural': '請假記錄'},
        ),
        migrations.AlterModelOptions(
            name='punch',
            options={'verbose_name': '打卡記錄', 'verbose_name_plural': '打卡記錄'},
        ),
    ]
