# Generated by Django 5.2.4 on 2025-07-21 16:33

import django.db.models.deletion
import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_leave_options_alter_punch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='work_schedule',
            field=models.ForeignKey(default=employee.models.get_default_work_schedule, on_delete=django.db.models.deletion.CASCADE, to='employee.workschedule', verbose_name='班別'),
        ),
    ]
