# Generated by Django 5.2.4 on 2025-07-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employeeschedule_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='員工編號'),
        ),
    ]
